# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libraryapi.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='libraryapi.proto',
  package='libraryapi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10libraryapi.proto\x12\nlibraryapi\x1a\x1bgoogle/protobuf/empty.proto\" \n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"0\n\rGetBooksReply\x12\x1f\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x10.libraryapi.Book\"\x1f\n\x11\x44\x65leteBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x84\x02\n\x07Library\x12?\n\x08GetBooks\x12\x16.google.protobuf.Empty\x1a\x19.libraryapi.GetBooksReply\"\x00\x12\x35\n\x07GetBook\x12\x16.google.protobuf.Empty\x1a\x10.libraryapi.Book\"\x00\x12:\n\x12\x43reateOrUpdateBook\x12\x10.libraryapi.Book\x1a\x10.libraryapi.Book\"\x00\x12\x45\n\nDeleteBook\x12\x1d.libraryapi.DeleteBookRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='libraryapi.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='libraryapi.Book.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='libraryapi.Book.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=93,
)


_GETBOOKSREPLY = _descriptor.Descriptor(
  name='GetBooksReply',
  full_name='libraryapi.GetBooksReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='books', full_name='libraryapi.GetBooksReply.books', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=143,
)


_DELETEBOOKREQUEST = _descriptor.Descriptor(
  name='DeleteBookRequest',
  full_name='libraryapi.DeleteBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='libraryapi.DeleteBookRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=176,
)

_GETBOOKSREPLY.fields_by_name['books'].message_type = _BOOK
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['GetBooksReply'] = _GETBOOKSREPLY
DESCRIPTOR.message_types_by_name['DeleteBookRequest'] = _DELETEBOOKREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'libraryapi_pb2'
  # @@protoc_insertion_point(class_scope:libraryapi.Book)
  })
_sym_db.RegisterMessage(Book)

GetBooksReply = _reflection.GeneratedProtocolMessageType('GetBooksReply', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKSREPLY,
  '__module__' : 'libraryapi_pb2'
  # @@protoc_insertion_point(class_scope:libraryapi.GetBooksReply)
  })
_sym_db.RegisterMessage(GetBooksReply)

DeleteBookRequest = _reflection.GeneratedProtocolMessageType('DeleteBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEBOOKREQUEST,
  '__module__' : 'libraryapi_pb2'
  # @@protoc_insertion_point(class_scope:libraryapi.DeleteBookRequest)
  })
_sym_db.RegisterMessage(DeleteBookRequest)



_LIBRARY = _descriptor.ServiceDescriptor(
  name='Library',
  full_name='libraryapi.Library',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=179,
  serialized_end=439,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBooks',
    full_name='libraryapi.Library.GetBooks',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GETBOOKSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBook',
    full_name='libraryapi.Library.GetBook',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_BOOK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateOrUpdateBook',
    full_name='libraryapi.Library.CreateOrUpdateBook',
    index=2,
    containing_service=None,
    input_type=_BOOK,
    output_type=_BOOK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteBook',
    full_name='libraryapi.Library.DeleteBook',
    index=3,
    containing_service=None,
    input_type=_DELETEBOOKREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIBRARY)

DESCRIPTOR.services_by_name['Library'] = _LIBRARY

# @@protoc_insertion_point(module_scope)
