# coding: utf-8

"""
    Library API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_user(self):
        """Test case for delete_user

        """
        pass

    def test_get_user(self):
        """Test case for get_user

        """
        pass

    def test_get_users(self):
        """Test case for get_users

        """
        pass

    def test_put_user(self):
        """Test case for put_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
